# git related
abbr gs "git status"
abbr gc "git checkout"
abbr gp "git pull"
abbr gpp "git push -u origin"
abbr gpu "git push -u upstream"
abbr gf "git fetch origin --prune"
abbr gfu "git fetch upstream --prune"
abbr gl "git log --all --decorate --oneline --graph"
abbr gcc "git fetch -p && git branch -vv | grep ': gone]' | awk '{print $1}' | xargs git branch -D"
abbr gcb "git checkout -b"
abbr gcm "git commit -m"
abbr gca "git commit --amend"
abbr gpp "git push -u origin"
abbr gd "git diff"
abbr gadd "git add ."
